Using Docker containers in Linux CI.

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -7,53 +7,74 @@ FROM ubuntu:23.10
 
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
-## Setup the common packages.
-RUN apt-get -y update
-RUN apt-get -y install curl gnupg lsb-release software-properties-common wget zip
+## Install the packages.
+RUN <<EOF
+  set -ex
+
+  # Install packages.
+  apt-get update -y
+  apt-get install -y                                                           \
+    build-essential                                                            \
+    cmake                                                                      \
+    curl                                                                       \
+    git                                                                        \
+    g++-13                                                                     \
+    gnupg                                                                      \
+    lsb-release                                                                \
+    ninja-build                                                                \
+    pkg-config                                                                 \
+    python3                                                                    \
+    python3-pip                                                                \
+    software-properties-common                                                 \
+    wget                                                                       \
+    zip
+
+  # Add LLVM.
+  wget -q https://apt.llvm.org/llvm.sh
+  chmod +x llvm.sh
+  ./llvm.sh 18
+  apt-get install -y clang-18 clang-tidy-18 libomp-18-dev
+
+  # Clean up.
+  apt-get -y clean
+  rm ./llvm.sh
+  rm -rf /var/lib/apt/lists/*
+EOF
 
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
-## Setup git.
-RUN apt-get -y install git
-RUN git config --global --add safe.directory '*'
-
-# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-
-## Setup the toolchain.
-ENV CXX=g++-13
-RUN apt-get -y install build-essential cmake g++-13 ninja-build pkg-config
-
-# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-
-## Install Python tools.
-RUN apt-get -y install python3 python3-pip
-RUN pip3 install --no-cache-dir --break-system-packages --upgrade codespell gcovr
-
-# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-
-## Install LLVM.
-RUN wget https://apt.llvm.org/llvm.sh
-RUN chmod +x llvm.sh
-RUN ./llvm.sh 18
-RUN apt-get -y install clang-18 clang-tidy-18 libomp-18-dev
+## Install the Python tools.
+RUN pip3 install --no-cache-dir --break-system-packages codespell gcovr
 
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
 ## Install vcpkg.
+ENV CXX=g++-13
 ENV VCPKG_ROOT=/root/vcpkg
-ENV VCPKG_DEFAULT_BINARY_CACHE=/root/vcpkg_cache
 ENV VCPKG_FORCE_SYSTEM_BINARIES=1
-RUN mkdir $VCPKG_DEFAULT_BINARY_CACHE
-RUN git clone --depth=1 https://github.com/microsoft/vcpkg.git $VCPKG_ROOT
-RUN $VCPKG_ROOT/bootstrap-vcpkg.sh
+RUN <<EOF
+  set -ex
 
-## Preinstall the manifested packages.
+  # Clone and bootstrap vcpkg.
+  git clone --depth=1 https://github.com/microsoft/vcpkg.git $VCPKG_ROOT
+  $VCPKG_ROOT/bootstrap-vcpkg.sh
+
+  # Clean up.
+  rm -rf $VCPKG_ROOT/CMakeFiles
+EOF
+
+# Install the manifested packages.
+ENV VCPKG_DEFAULT_BINARY_CACHE=/root/vcpkg_cache
 COPY vcpkg.json .
-RUN $VCPKG_ROOT/vcpkg install
+RUN <<EOF
+  set -ex
 
-# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+  # Install the manifested packages.
+  mkdir $VCPKG_DEFAULT_BINARY_CACHE
+  $VCPKG_ROOT/vcpkg install
 
-## Clean-up.
-RUN apt-get -y clean
+  # Clean up.
+  rm -rf $VCPKG_ROOT/buildtrees
+EOF
 
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
